# Stage3 - Scikit-learn으로 Random Forest 구현하기
## Data set 구성 계획 짜기
  
현재 우리는 데이터 보유량이 150개로 매우 적기 때문에 Validation Set은 만들지 않고  
최종적으로 150개 중 75%를 Training set으로 25%를 Test set으로 구성할 것.

## Training Set과 Validation Set 나누기
train_test_split 함수를 이용하여 Training Set과 Validation Set 나누기

In [1]:
import pandas as pd
df = pd.read_csv('data/iris.csv')
df

,Id,SepalLengthCm,SepalWidthCm,PetalLengthCm,PetalWidthCm,Species
0,1,5.1,3.5,1.4,0.2,Iris-setosa
1,2,4.9,3.0,1.4,0.2,Iris-setosa
2,3,4.7,3.2,1.3,0.2,Iris-setosa
3,4,4.6,3.1,1.5,0.2,Iris-setosa
4,5,5.0,3.6,1.4,0.2,Iris-setosa
...,...,...,...,...,...,...
145,146,6.7,3.0,5.2,2.3,Iris-virginica
146,147,6.3,2.5,5.0,1.9,Iris-virginica
147,148,6.5,3.0,5.2,2.0,Iris-virginica
148,149,6.2,3.4,5.4,2.3,Iris-virginica
149,150,5.9,3.0,5.1,1.8,Iris-virginica

In [6]:
input_data = df[['SepalLengthCm', 'SepalWidthCm', 'PetalLengthCm', 'PetalWidthCm']]
target_data = df['Species']

input_data

     SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm
0              5.1           3.5            1.4           0.2
1              4.9           3.0            1.4           0.2
2              4.7           3.2            1.3           0.2
3              4.6           3.1            1.5           0.2
4              5.0           3.6            1.4           0.2
..             ...           ...            ...           ...
145            6.7           3.0            5.2           2.3
146            6.3           2.5            5.0           1.9
147            6.5           3.0            5.2           2.0
148            6.2           3.4            5.4           2.3
149            5.9           3.0            5.1           1.8

[150 rows x 4 columns]

In [5]:
target_data

0         Iris-setosa
1         Iris-setosa
2         Iris-setosa
3         Iris-setosa
4         Iris-setosa
            ...
145    Iris-virginica
146    Iris-virginica
147    Iris-virginica
148    Iris-virginica
149    Iris-virginica
Name: Species, Length: 150, dtype: object

### train_test_split 함수

In [27]:
from sklearn.model_selection import train_test_split

x_train, x_test, y_train, y_test = train_test_split(input_data, target_data)

x_train

     SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm
62             6.0           2.2            4.0           1.0
127            6.1           3.0            4.9           1.8
31             5.4           3.4            1.5           0.4
18             5.7           3.8            1.7           0.3
51             6.4           3.2            4.5           1.5
..             ...           ...            ...           ...
71             6.1           2.8            4.0           1.3
15             5.7           4.4            1.5           0.4
46             5.1           3.8            1.6           0.2
12             4.8           3.0            1.4           0.1
69             5.6           2.5            3.9           1.1

[112 rows x 4 columns]

In [28]:
y_train

62     Iris-versicolor
127     Iris-virginica
31         Iris-setosa
18         Iris-setosa
51     Iris-versicolor
            ...
71     Iris-versicolor
15         Iris-setosa
46         Iris-setosa
12         Iris-setosa
69     Iris-versicolor
Name: Species, Length: 112, dtype: object

In [29]:
x_test.count()

SepalLengthCm    38
SepalWidthCm     38
PetalLengthCm    38
PetalWidthCm     38
dtype: int64

In [30]:
y_test.count()

38

In [31]:
x_train.count()

SepalLengthCm    112
SepalWidthCm     112
PetalLengthCm    112
PetalWidthCm     112
dtype: int64

## Decision Tree Classifier를 이용하여 학습, 평가

In [32]:
from sklearn.tree import DecisionTreeClassifier
tree = DecisionTreeClassifier() 
tree.fit(x_train, y_train)

print('training set accuracy: ', tree.score(x_train, y_train))
print('test set accuracy: ', tree.score(x_test, y_test))

# training set은 그대로(너무 쉬운 문제라), test set은 계속 바뀜.

training set accuracy:  1.0
test set accuracy:  0.8947368421052632

## Decision Tree 모델로 predict하기

In [33]:
# x_test의 test 결과
prediction = tree.predict(x_test)
prediction

array(['Iris-versicolor', 'Iris-virginica', 'Iris-virginica',
       'Iris-setosa', 'Iris-setosa', 'Iris-versicolor', 'Iris-versicolor',
       'Iris-versicolor', 'Iris-versicolor', 'Iris-setosa', 'Iris-setosa',
       'Iris-virginica', 'Iris-versicolor', 'Iris-virginica',
       'Iris-versicolor', 'Iris-versicolor', 'Iris-setosa', 'Iris-setosa',
       'Iris-versicolor', 'Iris-setosa', 'Iris-setosa', 'Iris-versicolor',
       'Iris-virginica', 'Iris-setosa', 'Iris-setosa', 'Iris-versicolor',
       'Iris-virginica', 'Iris-setosa', 'Iris-setosa', 'Iris-versicolor',
       'Iris-setosa', 'Iris-versicolor', 'Iris-versicolor',
       'Iris-versicolor', 'Iris-virginica', 'Iris-versicolor',
       'Iris-versicolor', 'Iris-setosa'], dtype=object)

In [34]:
x_test

     SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm
87             6.3           2.3            4.4           1.3
104            6.5           3.0            5.8           2.2
112            6.8           3.0            5.5           2.1
32             5.2           4.1            1.5           0.1
4              5.0           3.6            1.4           0.2
56             6.3           3.3            4.7           1.6
84             5.4           3.0            4.5           1.5
66             5.6           3.0            4.5           1.5
91             6.1           3.0            4.6           1.4
36             5.5           3.5            1.3           0.2
39             5.1           3.4            1.5           0.2
137            6.4           3.1            5.5           1.8
73             6.1           2.8            4.7           1.2
125            7.2           3.2            6.0           1.8
63             6.1           2.9            4.7           1.4
50             7.0           3.2            4.7           1.4
45             4.8           3.0            1.4           0.3
13             4.3           3.0            1.1           0.1
90             5.5           2.6            4.4           1.2
16             5.4           3.9            1.3           0.4
40             5.0           3.5            1.3           0.3
86             6.7           3.1            4.7           1.5
122            7.7           2.8            6.7           2.0
30             4.8           3.1            1.6           0.2
8              4.4           2.9            1.4           0.2
53             5.5           2.3            4.0           1.3
131            7.9           3.8            6.4           2.0
28             5.2           3.4            1.4           0.2
34             4.9           3.1            1.5           0.1
126            6.2           2.8            4.8           1.8
25             5.0           3.0            1.6           0.2
138            6.0           3.0            4.8           1.8
129            7.2           3.0            5.8           1.6
96             5.7           2.9            4.2           1.3
83             6.0           2.7            5.1           1.6
54             6.5           2.8            4.6           1.5
93             5.0           2.3            3.3           1.0
29             4.7           3.2            1.6           0.2

## Random Forest 구현해보기
Scikit-learn의 RandomForestClassifier 사용하기

In [49]:
# decision tree
# from sklearn.tree import DecisionTreeClassifier
# tree = DecisionTreeClassifier() 
# tree.fit(x_train, y_train)

# random forest
from sklearn.ensemble import RandomForestClassifier
forest = RandomForestClassifier(n_estimators = 100)
forest.fit(x_train, y_train)

print('training set accuracy: ', forest.score(x_train, y_train))
print('test set accuracy: ', forest.score(x_test, y_test))

training set accuracy:  1.0
test set accuracy:  0.9210526315789473

## Random Forest 모델로 predict하기

In [46]:
#decision tree
# prediction = tree.predict(x_test)
# prediction

# random forest
prediction_by_forest = forest.predict(x_test)
prediction_by_forest

array(['Iris-versicolor', 'Iris-virginica', 'Iris-virginica',
       'Iris-setosa', 'Iris-setosa', 'Iris-versicolor', 'Iris-versicolor',
       'Iris-versicolor', 'Iris-versicolor', 'Iris-setosa', 'Iris-setosa',
       'Iris-virginica', 'Iris-versicolor', 'Iris-virginica',
       'Iris-versicolor', 'Iris-versicolor', 'Iris-setosa', 'Iris-setosa',
       'Iris-versicolor', 'Iris-setosa', 'Iris-setosa', 'Iris-versicolor',
       'Iris-virginica', 'Iris-setosa', 'Iris-setosa', 'Iris-versicolor',
       'Iris-virginica', 'Iris-setosa', 'Iris-setosa', 'Iris-virginica',
       'Iris-setosa', 'Iris-versicolor', 'Iris-virginica',
       'Iris-versicolor', 'Iris-virginica', 'Iris-versicolor',
       'Iris-versicolor', 'Iris-setosa'], dtype=object)